/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/myShoes.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MyShoes(props) {
  const { nodes, materials } = useGLTF('/models/myShoes.glb')
  return (
    <group {...props} dispose={null} rotation={[0, 2.5, 0]}>
      <mesh geometry={nodes.Telapak004.geometry} material={materials['Material.008']} position={[0, -0.019, 0]} scale={[1.045, 1, 1]} />
      <mesh geometry={nodes.BezierCurve004.geometry} material={materials['Material.010']} position={[0, 0.985, 0.566]} rotation={[1.471, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.BezierCurve006.geometry} material={materials['Material.009']} position={[0, 0.767, 2.104]} rotation={[0.888, 0, -Math.PI / 2]} scale={0.601} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Cube007_3.geometry} material={materials['Material.014']} />
    </group>
  )
}

useGLTF.preload('/models/myShoes.glb')
